version: 0.2

phases:
  install:
    commands:
<<<<<<< HEAD
      - npm install
=======
      - echo Installing dependencies...
      - npm install --force
  pre_build:
    commands:
      - echo Retrieving API Gateway URL from CloudFormation
      - API_GATEWAY_URL=$(aws cloudformation describe-stacks \
          --stack-name your-stack-name \
          --query "Stacks[0].Outputs[?OutputKey=='ApiGatewayURL'].OutputValue" \
          --output text)
      - echo API Gateway URL is $API_GATEWAY_URL
      - export REACT_APP_API_URL=$API_GATEWAY_URL
>>>>>>> 002bd596297d9f1e2caf0c9f9914bcbb64e124ca
  build:
    commands:
      - npm run build  # Builds the project
artifacts:
  files:
    - '**/*'
  base-directory: build  # Directory with output files (e.g., React app )